"""Lista simplificada dos algoritmos disponíveis para o prompt do LLM."""

ALGORITHM_INDEX = [
    {"id": "dor-abdominal", "name": "Dor Abdominal", "category": "Digestivo", "kw": "dor abdominal, cólica, epigastralgia, apendicite, peritonite, melena"},
    {"id": "cefaleia", "name": "Cefaleia", "category": "Neurológico", "kw": "cefaleia, dor de cabeça, enxaqueca, meningite, fotofobia, AVC"},
    {"id": "dor-toracica", "name": "Dor Torácica", "category": "Cardiovascular", "kw": "dor torácica, precordialgia, angina, enfarte, SCA, aperto no peito"},
    {"id": "problema-ocular", "name": "Problema Ocular", "category": "Oftalmológico", "kw": "visão, olho, trauma ocular, glaucoma, diplopia, olho vermelho"},
    {"id": "tensao-arterial", "name": "Problema de Tensão Arterial", "category": "Cardiovascular", "kw": "hipertensão, HTA, pré-eclâmpsia, crise hipertensiva, hipotensão"},
    {"id": "problema-urinario", "name": "Problema Urinário", "category": "Genito-Urinário", "kw": "infeção urinária, hematúria, pielonefrite, litíase renal, disúria"},
    {"id": "saude-homem", "name": "Problema de Saúde do Homem", "category": "Genito-Urinário", "kw": "torção testicular, priapismo, balanite, IST, parafimose"},
    {"id": "amamentacao", "name": "Problema na Amamentação", "category": "Materno-Infantil", "kw": "amamentação, mastite, galactorreia, lesão mamária"},
    {"id": "crianca-chora", "name": "Criança que Chora (0-1 ano)", "category": "Materno-Infantil", "kw": "choro bebé, febre lactente, irritabilidade, dentição"},
    {"id": "problema-face", "name": "Problema na Face", "category": "Cabeça e Pescoço", "kw": "sinusite, trauma facial, rash facial, dor de dentes, herpes zoster"},
    {"id": "obstipacao", "name": "Obstipação", "category": "Digestivo", "kw": "obstipação, prisão de ventre, hemorragia retal, hemorróidas"},
    {"id": "geriatrico", "name": "Problemas Geriátricos", "category": "Geriatria", "kw": "idoso, queda, confusão, demência, incontinência"},
    {"id": "integridade-cutanea", "name": "Integridade Cutânea", "category": "Dermatológico", "kw": "ferida, lesão da pele, corpo estranho, contusão, urticária"},
    {"id": "queimaduras", "name": "Queimaduras", "category": "Dermatológico", "kw": "queimadura térmica, química, elétrica, escaldão solar"},
    {"id": "diabetes", "name": "Diabetes", "category": "Endocrinologia", "kw": "hipoglicemia, hiperglicemia, cetoacidose, pé diabético"},
    {"id": "inespecifico", "name": "Problemas Inespecíficos", "category": "Outros", "kw": "sintoma inespecífico, informação, MSRM"},
    {"id": "alergias", "name": "Alergias", "category": "Imunoalergologia", "kw": "alergia, anafilaxia, urticária, picada de inseto, reação medicamentosa"},
    {"id": "corpo-estranho", "name": "Corpo Estranho (Inalação/Aspiração)", "category": "Respiratório", "kw": "engasgamento, aspiração, asfixia, obstrução via aérea"},
    {"id": "intoxicacao", "name": "Ingestão de Substâncias Tóxicas", "category": "Outros", "kw": "intoxicação, overdose, veneno, CIAV"},
    {"id": "cabeca-pescoco", "name": "Cabeça e Pescoço (Traumatismo)", "category": "Trauma", "kw": "TCE, traumatismo craniano, cervical, queda"},
    {"id": "msk-ombro", "name": "Ombro / Clavícula / Braço", "category": "Músculo-Esquelético", "kw": "ombro, clavícula, braço, fratura, hematoma"},
    {"id": "msk-cotovelo", "name": "Cotovelo", "category": "Músculo-Esquelético", "kw": "cotovelo, fratura, traumatismo"},
    {"id": "msk-punho-mao", "name": "Punho / Mão", "category": "Músculo-Esquelético", "kw": "punho, mão, túnel cárpico, fratura"},
    {"id": "msk-anca", "name": "Anca", "category": "Músculo-Esquelético", "kw": "anca, fémur, ciatalgia"},
    {"id": "msk-joelho", "name": "Joelho", "category": "Músculo-Esquelético", "kw": "joelho, fratura, ligamento"},
    {"id": "msk-tornozelo-pe", "name": "Tornozelo / Pé", "category": "Músculo-Esquelético", "kw": "tornozelo, pé, entorse, luxação"},
    {"id": "msk-dedos", "name": "Dedos", "category": "Músculo-Esquelético", "kw": "dedo, fratura, frieiras"},
    {"id": "depressao", "name": "Depressão", "category": "Saúde Mental", "kw": "depressão, tristeza, ideação suicida, anedonia"},
    {"id": "ansiedade", "name": "Ansiedade", "category": "Saúde Mental", "kw": "ansiedade, pânico, palpitações, medo"},
    {"id": "vacinacao", "name": "Reação a Vacinação", "category": "Preventiva", "kw": "vacina, reação vacinal, febre pós-vacina"},
    {"id": "tonturas", "name": "Tonturas / Vertigem", "category": "Neurológico", "kw": "vertigem, tontura, labirintite, síncope"},
    {"id": "lombalgia", "name": "Lombalgia", "category": "Músculo-Esquelético", "kw": "lombalgia, ciática, hérnia discal, coluna"},
    {"id": "desmaio", "name": "Desmaio / Lipotímia", "category": "Cardiovascular", "kw": "síncope, lipotímia, desmaio"},
    {"id": "cor-fezes", "name": "Alteração da Cor das Fezes", "category": "Digestivo", "kw": "melenas, fezes brancas, sangue nas fezes, hemorroidas"},
    {"id": "crise-adaptacao", "name": "Adaptação em Situação de Crise", "category": "Saúde Mental", "kw": "luto, catástrofe, crise, trauma psicológico"},
    {"id": "respiratorio-agudo", "name": "Problema Respiratório Agudo", "category": "Respiratório", "kw": "dispneia, tosse, asma, gripe, sibilos"},
    {"id": "nauseas-vomitos", "name": "Náuseas e Vómitos (Adulto)", "category": "Digestivo", "kw": "náuseas, vómitos, hematémese, desidratação"},
    {"id": "diarreia", "name": "Diarreia (Adulto)", "category": "Digestivo", "kw": "diarreia, gastroenterite, desidratação"},
    {"id": "rash", "name": "Rash (Adulto)", "category": "Dermatológico", "kw": "exantema, rash, petéquias, urticária"},
    {"id": "sarampo", "name": "Suspeita de Sarampo", "category": "Infeciologia", "kw": "sarampo, exantema, Koplik, contacto"},
    {"id": "orofaringe", "name": "Orofaringe (Adulto)", "category": "Cabeça e Pescoço", "kw": "dor de garganta, amigdalite, faringite, odinofagia"},
    {"id": "gravidez", "name": "Problema na Gravidez", "category": "Materno-Infantil", "kw": "gravidez, pré-eclâmpsia, hemorragia vaginal, trabalho de parto"},
    {"id": "ginecologico-12mais", "name": "Ginecológico/Mamário (>=12 anos)", "category": "Ginecológico", "kw": "dor genital, infeção ginecológica, mastite"},
    {"id": "saude-mulher", "name": "Saúde da Mulher (>=12 anos, não grávida)", "category": "Ginecológico", "kw": "hemorragia genital, dor genital, infeção mamária"},
    {"id": "pos-cirurgia-gin", "name": "Após Cirurgia Ginecológica/Mamária", "category": "Ginecológico", "kw": "pós-operatório, infeção cicatriz, hemorragia"},
    {"id": "puerperio", "name": "Puerpério / Pós-Abortamento", "category": "Materno-Infantil", "kw": "puerpério, hemorragia pós-parto, mastite"},
    {"id": "ouvido", "name": "Problema do Ouvido", "category": "Cabeça e Pescoço", "kw": "otalgia, otite, acufenos, surdez, otorreia"},
    {"id": "ginecologico-menor12", "name": "Ginecológico/Mamário (<12 anos)", "category": "Ginecológico", "kw": "patologia pediátrica, trauma genital criança"},
    {"id": "temperatura", "name": "Alteração da Temperatura (Adulto)", "category": "Infeciologia", "kw": "febre, hipertermia, hipotermia, golpe de calor"},
    {"id": "exposicao-solar", "name": "Exposição Solar / Calor", "category": "Ambiental", "kw": "golpe de calor, insolação, escaldão solar, desidratação"},
]

BY_ID = {a["id"]: a for a in ALGORITHM_INDEX}
